area/github-management:
  - changed-files:
      - any-glob-to-any-file:
          - '**/.github/**'
          - '**/.github/**/*'

area/test:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*.test.ts'
          - 'src/*.spec.ts'
          - 'src/**/*.spec.ts'
          - '__tests__/**/*.ts'

area/documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - '**/*.txt'
